# -*- coding: utf-8 -*-
"""United Kingdom Top 50 Playlist Market Structure, Artist Diversity & ContentLocalization Analysis app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KI3tc0nQ4WYPtLIZMJcaI3MzwA-OUrMD
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv("/content/Atlantic_United_Kingdom.csv")

data.head()

data.shape

data.index

data.columns

data.info()

"""Data Validation and standardization

  • Validate daily Top 50
  
  • Normalize artist names
  
  • Split multi-artist collaborations using delimiter (&)
"""

data['date'] = pd.to_datetime(data['date'], format='%d-%m-%Y')

daily_counts = data['date'].value_counts().sort_index()
display(daily_counts.head())

"""Let's check for dates that do not have exactly 50 entries."""

dates_with_non_50_entries = daily_counts[daily_counts != 50]

if dates_with_non_50_entries.empty:
    print("All dates have exactly 50 entries.")
else:
    print("Dates with an entry count not equal to 50:")
    display(dates_with_non_50_entries)

data['artist'] = data['artist'].str.strip().str.lower()

display(data.head())

data['artist'] = data['artist'].str.split('&').explode('artist')
data['artist'] = data['artist'].str.strip()

display(data.head())

data['duration_minutes'] = (data['duration_ms'] / 60000).astype(int)
data['duration_seconds'] = ((data['duration_ms'] % 60000) / 1000).astype(int)

display(data[['duration_ms', 'duration_minutes', 'duration_seconds']].head())

"""Artist Dominance & Diversity Analysis

• Count unique artists per day

• Measure total appearances per artist

• Identify top-dominating artists

• Compute Artist Concentration Index
"""

unique_artists_per_day = data.groupby('date')['artist'].nunique().reset_index()
unique_artists_per_day.rename(columns={'artist': 'unique_artist_count'}, inplace=True)
display(unique_artists_per_day.head())

"""This table shows the number of unique artists featured on the charts for each day."""

artist_appearances = data['artist'].value_counts()

top_5_artists = artist_appearances.head(5)
display(top_5_artists)

total_appearances = artist_appearances.sum()
top_5_appearances = top_5_artists.sum()

aci = (top_5_appearances / total_appearances) * 100
print(f"Artist Concentration Index (ACI) based on Top 5 artists: {aci:.2f}%")

"""The Artist Concentration Index (ACI) shows the percentage of total appearances accounted for by the top 5 artists. A higher ACI suggests greater dominance by a few artists.

### Leaderboard of Most Frequent Charting Artists
"""

display(artist_appearances)

"""### Domestic vs. International Artist Comparison

To compare domestic and international artists, we first need to categorize them. This involves creating a list of known domestic (UK) artists.
"""

# Placeholder for domestic artists.
domestic_artists_list = ['adele', 'ed sheeran', 'coldplay', 'dua lipa', 'harry styles', 'stormzy', 'elton john', 'queen', 'the beatles', 'sam smith', 'calvin harris', 'ellie goulding', 'lewis capaldi', 'dave', 'lil peep', 'drake'] # Added a few more for illustration

data['artist_origin'] = data['artist'].apply(lambda x: 'Domestic' if x in domestic_artists_list else 'International')
display(data[['artist', 'artist_origin']].head())

"""Collaboration Structure Analysis

• Identify solo vs collaborative tracks

• Average collaborators per song

• Collaboration frequency by rank group (Top 10, Top 50)

• Artist collaboration network graph
"""

# Remove any existing 'collaboration_type' columns (e.g., _x, _y suffixes) to ensure clean merge on re-run
columns_to_drop = [col for col in data.columns if col.startswith('collaboration_type')]
if columns_to_drop:
    data = data.drop(columns=columns_to_drop)

collaboration_status = data.groupby(['date', 'song'])['artist'].nunique().reset_index()
collaboration_status['collaboration_type'] = collaboration_status['artist'].apply(lambda x: 'Collaboration' if x > 1 else 'Solo')

# Merge to add the collaboration_type to the main DataFrame

data = pd.merge(data, collaboration_status[['date', 'song', 'collaboration_type']], on=['date', 'song'], how='left')
display(data[['date', 'song', 'artist', 'collaboration_type']].head())

collaboration_counts = collaboration_status['collaboration_type'].value_counts()
total_unique_songs = collaboration_counts.sum()

collaborative_songs = collaboration_counts.get('Collaboration', 0)
collaboration_ratio = (collaborative_songs / total_unique_songs) * 100

print(f"Total unique songs: {total_unique_songs}")
print(f"Collaborative songs: {collaborative_songs}")
print(f"Collaboration Ratio: {collaboration_ratio:.2f}%")

# Filter data for Top 10 and Top 50 songs

top_10_songs = data[data['position'] <= 10]
top_50_songs = data[data['position'] <= 50]

# Calculate collaboration counts for Top 10

top_10_collaboration_counts = top_10_songs['collaboration_type'].value_counts()
top_10_total_songs = top_10_collaboration_counts.sum()
top_10_collaborative_songs = top_10_collaboration_counts.get('Collaboration', 0)
top_10_collaboration_ratio = (top_10_collaborative_songs / top_10_total_songs) * 100 if top_10_total_songs > 0 else 0

# Calculate collaboration counts for Top 50

top_50_collaboration_counts = top_50_songs['collaboration_type'].value_counts()
top_50_total_songs = top_50_collaboration_counts.sum()
top_50_collaborative_songs = top_50_collaboration_counts.get('Collaboration', 0)
top_50_collaboration_ratio = (top_50_collaborative_songs / top_50_total_songs) * 100 if top_50_total_songs > 0 else 0

print(f"Collaboration Frequency in Top 10 Songs: {top_10_collaboration_ratio:.2f}%")
print(f"Collaboration Frequency in Top 50 Songs: {top_50_collaboration_ratio:.2f}%")

import networkx as nx
import matplotlib.pyplot as plt

"""### Collaboration Network Graph

To visualize the collaboration network, we'll create a graph where nodes are artists and an edge exists between two artists if they have collaborated on a song.
"""

# Filter for collaborative songs
collaborative_songs_df = data[data['collaboration_type'] == 'Collaboration']

# Create a graph
G = nx.Graph()

# Add nodes and edges based on collaborations
for idx, row in collaborative_songs_df.iterrows():
    song = row['song']
    artists_in_song = collaborative_songs_df[(collaborative_songs_df['date'] == row['date']) & (collaborative_songs_df['song'] == song)]['artist'].tolist()

    # Add nodes (artists)
    for artist in artists_in_song:
        G.add_node(artist)

    # Add edges between collaborating artists in the same song
    for i in range(len(artists_in_song)):
        for j in range(i + 1, len(artists_in_song)):
            G.add_edge(artists_in_song[i], artists_in_song[j])

print(f"Number of nodes (artists involved in collaborations): {G.number_of_nodes()}")
print(f"Number of edges (collaborations): {G.number_of_edges()}")

# Visualize the collaboration network
plt.figure(figsize=(15, 12))
pos = nx.spring_layout(G, k=0.15, iterations=20)  # position nodes using Fruchterman-Reingold force-directed algorithm
nx.draw_networkx_nodes(G, pos, node_size=200, node_color='skyblue')
nx.draw_networkx_edges(G, pos, width=1, alpha=0.5, edge_color='gray')
nx.draw_networkx_labels(G, pos, font_size=8, font_weight='bold')
plt.title('Artist Collaboration Network', size=20)
plt.axis('off')
plt.show()

"""Content Explicitness Analysis

• Explicit vs non-explicit share

• Explicit content distribution by rank

• Cultural sensitivity insights for UK listeners
"""

# Calculate the count of explicit and non-explicit tracks
explicit_counts = data['is_explicit'].value_counts()
total_tracks = explicit_counts.sum()

# Calculate the percentage of explicit tracks
explicit_percentage = (explicit_counts[True] / total_tracks) * 100 if True in explicit_counts else 0

print(f"Total tracks: {total_tracks}")
print(f"Explicit tracks: {explicit_counts.get(True, 0)}")
print(f"Non-explicit tracks: {explicit_counts.get(False, 0)}")
print(f"Percentage of explicit tracks: {explicit_percentage:.2f}%")

"""### Explicit Content Distribution by Rank Group

Let's analyze how explicit content is distributed across different chart positions. We'll categorize songs into three groups: Top 10, Top 11-50, and Top 51+.
"""

# Define rank groups

top_10_explicit = data[data['position'] <= 10]['is_explicit'].value_counts(normalize=True).mul(100).reindex([False, True], fill_value=0).rename('Top 10')
top_11_50_explicit = data[(data['position'] > 10) & (data['position'] <= 50)]['is_explicit'].value_counts(normalize=True).mul(100).reindex([False, True], fill_value=0).rename('Top 11-50')
top_51_plus_explicit = data[data['position'] > 50]['is_explicit'].value_counts(normalize=True).mul(100).reindex([False, True], fill_value=0).rename('Top 51+')

# Combine the results into a single DataFrame for easier plotting

explicit_distribution_by_rank = pd.DataFrame({
    'Top 10': top_10_explicit,
    'Top 11-50': top_11_50_explicit,
    'Top 51+': top_51_plus_explicit
}).T # Transpose. fillna(0) is no longer needed as reindex handles missing values.

explicit_distribution_by_rank = explicit_distribution_by_rank.fillna(0)
explicit_distribution_by_rank.columns = ['Clean', 'Explicit'] # Rename columns for clarity

display(explicit_distribution_by_rank)

import matplotlib.pyplot as plt

# Plotting the distribution

fig, ax = plt.subplots(figsize=(10, 6))
explicit_distribution_by_rank.plot(kind='bar', stacked=True, ax=ax, color=['lightgreen', 'salmon'])

plt.title('Percentage of Explicit vs. Clean Tracks by Rank Group', fontsize=16)
plt.xlabel('Rank Group', fontsize=12)
plt.ylabel('Percentage (%)', fontsize=12)
plt.xticks(rotation=0) # Keep x-axis labels horizontal
plt.legend(title='Content Type', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()



"""Album Structure & Release Strategy Analysis

• Single vs album track presence

• Album size (total_tracks) vs playlist inclusion

• Release format dominance in the UK market

### Single vs Album Track Presence

We'll analyze the distribution of tracks by their `album_type` to understand the presence of singles versus album tracks in the charts.
"""

# Calculate the counts of each album type

album_type_counts = data['album_type'].value_counts()

display(album_type_counts)

# Calculate the ratio of singles to album tracks

singles_count = album_type_counts.get('single', 0)
album_tracks_count = album_type_counts.get('album', 0)

if album_tracks_count > 0:
    single_album_ratio = singles_count / album_tracks_count
    print(f"\nRatio of Singles to Album Tracks: {single_album_ratio:.2f}:1")
else:
    print("\nNo album tracks found in the dataset to compute the ratio.")

"""### Album Size (`total_tracks`) vs. Playlist Inclusion Likelihood

We'll examine how the number of tracks in an album (or single/compilation) correlates with a track's appearance in the charts and its average popularity. Tracks from singles will have `total_tracks=1`.
"""

# Calculate the frequency of chart entries for each 'total_tracks' value

playlist_inclusion_by_album_size = data['total_tracks'].value_counts().sort_index()

print("Frequency of Tracks in Chart by Album Size:")
display(playlist_inclusion_by_album_size.head(10))

# Visualize the frequency

plt.figure(figsize=(14, 7))
sns.barplot(x=playlist_inclusion_by_album_size.index, y=playlist_inclusion_by_album_size.values, palette='viridis')
plt.title('Frequency of Tracks in Chart by Album Size', fontsize=16)
plt.xlabel('Total Tracks in Album/Single', fontsize=12)
plt.ylabel('Number of Chart Entries', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Calculate the average popularity for tracks based on their 'total_tracks' value

avg_popularity_by_album_size = data.groupby('total_tracks')['popularity'].mean().sort_index()

print("\nAverage Popularity of Tracks in Chart by Album Size:")
display(avg_popularity_by_album_size.head(10))

# Visualize the average popularity

plt.figure(figsize=(14, 7))
sns.lineplot(x=avg_popularity_by_album_size.index, y=avg_popularity_by_album_size.values, marker='o', color='purple')
plt.title('Average Popularity of Tracks in Chart by Album Size', fontsize=16)
plt.xlabel('Total Tracks in Album/Single', fontsize=12)
plt.ylabel('Average Popularity', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.7)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""### Release Format Dominance in the UK Market (Singles vs. Albums)

Based on the `album_type_counts`, we can directly assess the dominance of singles versus albums in the charted tracks.
"""

# Use the pre-computed album_type_counts

display(album_type_counts)

# Visualize the distribution of album types

plt.figure(figsize=(8, 6))
sns.barplot(x=album_type_counts.index, y=album_type_counts.values, palette='pastel')
plt.title('Distribution of Album Types in UK Chart Data', fontsize=16)
plt.xlabel('Album Type', fontsize=12)
plt.ylabel('Number of Chart Entries', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Conclude based on the counts

singles_count = album_type_counts.get('single', 0)
album_count = album_type_counts.get('album', 0)
compilation_count = album_type_counts.get('compilation', 0)

if album_count > singles_count:
    print(f"\nIn this dataset, albums ({album_count} entries) are more dominant than singles ({singles_count} entries) in the UK chart.")
elif singles_count > album_count:
    print(f"\nIn this dataset, singles ({singles_count} entries) are more dominant than albums ({album_count} entries) in the UK chart.")
else:
    print(f"\nSingles and albums have an equal presence in the UK chart based on this dataset ({singles_count} entries each).")

print(f"Compilation entries: {compilation_count}")

"""Track Duration & Format Analysis
Using:

• Duration distribution (short-form vs long-form)

• Duration vs popularity bucket analysis

• UK listener preference indicators

### Track Duration Distribution

Let's visualize the distribution of track durations in minutes to understand common song lengths.
"""

plt.figure(figsize=(10, 6))
sns.histplot(data['duration_minutes'], bins=30, kde=True, color='skyblue')
plt.title('Distribution of Track Durations (Minutes)', fontsize=16)
plt.xlabel('Duration (Minutes)', fontsize=12)
plt.ylabel('Number of Tracks', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### Categorizing Track Durations into Buckets

Now, let's categorize the tracks into 'short' (<180s), 'medium' (180-240s), and 'long' (>240s) durations to further analyze their distribution and characteristics.
"""

def categorize_duration(seconds):
    if seconds < 180:
        return 'Short'
    elif 180 <= seconds <= 240:
        return 'Medium'
    else:
        return 'Long'

data['duration_bucket'] = (data['duration_minutes'] * 60 + data['duration_seconds']).apply(categorize_duration)

display(data[['song', 'duration_minutes', 'duration_seconds', 'duration_bucket']].head())

"""### Duration vs. Popularity Score

Let's examine if there's a correlation between track duration and its average popularity score.
"""

# Calculate the average popularity for each duration bucket

avg_popularity_by_duration = data.groupby('duration_bucket')['popularity'].mean().reindex(['Short', 'Medium', 'Long'])

print("Average Popularity by Duration Bucket:")
display(avg_popularity_by_duration)

# Visualize the average popularity by duration bucket

plt.figure(figsize=(10, 6))
sns.barplot(x=avg_popularity_by_duration.index, y=avg_popularity_by_duration.values, palette='viridis')
plt.title('Average Popularity by Track Duration Bucket', fontsize=16)
plt.xlabel('Duration Bucket', fontsize=12)
plt.ylabel('Average Popularity', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""### UK Listener Preference Indicators: Duration Distribution

To understand listener preferences based on track duration, let's look at the frequency of each duration bucket in the chart data.
"""

# Calculate the counts for each duration bucket

duration_bucket_counts = data['duration_bucket'].value_counts().reindex(['Short', 'Medium', 'Long'])

print("Distribution of Track Duration Buckets:")
display(duration_bucket_counts)

# Visualize the distribution

plt.figure(figsize=(8, 6))
sns.barplot(x=duration_bucket_counts.index, y=duration_bucket_counts.values, palette='plasma')
plt.title('Distribution of Track Duration Buckets in UK Chart Data', fontsize=16)
plt.xlabel('Duration Bucket', fontsize=12)
plt.ylabel('Number of Tracks', fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""Market Structure Metrics
Using:

• Playlist concentration ratio (Top 5 artists share)

• Diversity score (unique artists / total entries)

• Content variety index
"""

artist_counts = data['artist'].value_counts()

# Top 5 artists total appearances
top5_share = artist_counts.head(5).sum()

# Total entries in dataset
total_entries = len(data)

# Concentration ratio
concentration_ratio = top5_share / total_entries
print("Playlist Concentration Ratio:", concentration_ratio)

"""### Diversity Score (Unique Artists / Total Entries)"""

total_entries = len(data)
unique_artists = data['artist'].nunique()
diversity_score = unique_artists / total_entries

print(f"Total unique artists: {unique_artists}")
print(f"Total chart entries: {total_entries}")
print(f"Diversity Score (Unique Artists / Total Entries): {diversity_score:.4f}")

"""### Content Variety Index (Unique Songs / Total Entries)"""

unique_songs = data['song'].nunique()
content_variety_index = unique_songs / total_entries

print(f"Total unique songs: {unique_songs}")
print(f"Total chart entries: {total_entries}")
print(f"Content Variety Index (Unique Songs / Total Entries): {content_variety_index:.4f}")

